### ISSUE TITLE
`ChatSession` don't inherit `generationConfig` from `GenerativeModel`

### ISSUE THREAD

**Issue by Rodrigodd** [google/generative-ai-js#101]
## Actual Behavior

The [docs](https://ai.google.dev/tutorials/get_started_node#model-parameters) mention that you can pass model parameters to `genAI.getGenerativeModel.getGenerativeModel`:

```
const generationConfig = {
  stopSequences: ["red"],
  maxOutputTokens: 200,
  temperature: 0.9,
  topP: 0.1,
  topK: 16,
};

const model = genAI.getGenerativeModel({ model: "MODEL_NAME",  generationConfig });
```

But if you pass the parameters there, they are silently ignored when using [`model.startChat` API](https://ai.google.dev/tutorials/get_started_node#multi-turn-conversations-chat). You need to pass these parameters directly to `startChat`, even though it is already a method of `GenerativeModel`.

I confirmed that by making the requests through a proxy (https://httptoolkit.com/).

The same applies for `safetySettings`.

## Expected Behavior

`model.startChat` should inherit `generationConfig`, `safetySettings`, etc., from `model`.

## Specifications

- Version: 0.6.0
- Platform: Windows

**Comment by hsubox76** [comment]
This seems to be a bug, will look into fixing.

**Comment by zakcali** [comment]
is this sequence behaves correct? I'm using this parameters:
`    const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest",  systemInstruction: { role: "system", parts: [{ text: "your name is bob" }] }, }, { apiVersion: 'v1beta', generationConfig, safetySettings });`

**Comment by hsubox76** [comment]
No, the original code snippet is not exactly correct but I think it's just a typo, generationConfig definitely wasn't getting passed to chatSession, working on fixing this. I think your code snippet is also incorrect, generationConfig and safetySettings should be in the first object, not the second.
