### ISSUE TITLE
Fetching error occurred when some regions can't access the API server

### ISSUE THREAD

**Issue by Emirateyang** [google/generative-ai-js#16]
## Expected Behavior
Some regions can't access the API directly, so it's cause fetching error.

## Actual Behavior
Is it possible to add proxy when the model is sending message to google AI API endpoint? 
Thanks

## Specifications

- Version:
- Platform:

**Comment by berkaltiok** [comment]
You're using Vercel?

**Comment by marb2000** [comment]
Thanks for opening this issue. Unfortunately, currently Google AI Studio doesn't support access to its services via proxy. Additionally, please be aware that the [Google AI Studio Terms of Service](https://ai.google.dev/terms) restrict access to Services and API Clients within [available regions](https://ai.google.dev/available_regions). While we can't share specific region names or timelines at this time, we're actively expanding access as quickly as possible and will keep you posted on any progress.

Thank you for your understanding and continued support.

**Comment by marb2000** [comment]
Assuming that allowing the use of a proxy has the goal of enabling access for clients from unavailable regions, I'm tagging this as "Won't fix".

**Comment by Emirateyang** [comment]
Thank you. I got it.

**Comment by GulgDev** [comment]
> Assuming that allowing the use of a proxy has the goal of enabling access for clients from unavailable regions, I'm tagging this as "Won't fix".

Excuse me, what are the actual reasons that there are "unavailable regions"? Are there technical limitations that make it impossible to serve customers in specific regions?
