### ISSUE TITLE
Chat conversation with a system role

### ISSUE THREAD

**Issue by Ranork** [google/generative-ai-js#23]
Can we use a system role in chat history to provide instructions to model?

For example:
```json
{
"role": "system",
"parts": "You are an sql generator and your platform is MSSQL."
}
```

**Comment by haraldschilly** [comment]
I was not able to find something like that as well, but my idea was to "fake" the historial interaction. I.e. at [CoCalc](https://github.com/sagemathinc/cocalc/blob/ef109dd9408879fecdd59b77a58c2208d9461032/src/packages/server/llm/vertex-ai-client.ts#L140) such a system prompt is converted to starting the conversation as:

```js
[
  { role: "user", parts: `SYSTEM CONTEXT:\n${context}` },
  { role: "model", parts: "OK" },
]
```

It's really doing something along the lines I would expect!

**Comment by Ranork** [comment]
Yeah it seems work for now. Thanks!

**Comment by enricoros** [comment]
I'm using the same conversion - but the next issue is how to deal with sequential messages from the user or the assistant.
This code seems to be working well so far: https://github.com/enricoros/big-AGI/blob/0fc83cf6f5d0c62bb0cc7bc29b8bf6d22d3caa99/src/modules/llms/server/gemini/gemini.router.ts#L55-L76
