### ISSUE TITLE
Can BASE_URL be modified?

### ISSUE THREAD

**Issue by classfang** [google/generative-ai-js#25]

**Comment by leason-wan** [comment]
this is I want too... workaround with restfull api :)

**Comment by classfang** [comment]
I might use an official platform agent api like vercel, which openai.js supports.

**Comment by yokingma** [comment]
I need this too...

**Comment by dalefengs** [comment]
I need this too...

**Comment by hsubox76** [comment]
The most helpful thing in getting this feature approved would be if everyone who needs this could provide their use cases with as much detail as possible. Links to products you want to work with (e.g., Vercel's platform agent API?), blog posts or documentation describing cases where this is needed, etc., would be especially helpful.
