### ISSUE TITLE
I couldn't use PassThrough to return the response.

### ISSUE THREAD

**Issue by white-z** [google/generative-ai-js#33]
## Expected Behavior
respond to messages in a word-for-word or line-by-line manner

## Actual Behavior
Getting errors or always responding to all messages at once

## Steps to Reproduce the Problem

1.I was trying to return an event stream using Koa and ran into an error. Here's a snippet of the code from the Node.js route:
```typescript
  import { PassThrough, pipeline } from 'stream'
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel(modelParams)
  const chat = model.startChat(startChatParams) 
  const sseStream = new PassThrough({ objectMode: true })
  const res = await chat.sendMessageStream(prompt)
  pipeline(res.stream, sseStream);
  ctx.body = sseStream
```
This is the error message after running: 
```txt
The "streams[stream.length - 1]" property must be of type function. Received an instance of PassThrough
```
2. I tried responding in a different way:
```typescript
import { Transform } from 'stream'
class SSEStream extends Transform {
  constructor() {
    super({
      writableObjectMode: true
    });
  }
  _transform(data: any, _encoding: any, done: () => void) {
    try {
      this.push(`data: ${JSON.stringify(data)}\n\n`);
      done();
    } catch (error) {
      done();
    }
  }
}
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  // ...
  const res = await chat.sendMessageStream(prompt)
  const sseStream = new SSEStream()
  ctx.body = sseStream
  for await (const chunk of res.stream) {
    const chunkText = chunk.text();
    sseStream.write(chunkText);
  }
```
The client will only receive the final complete message once, instead of getting it line by line. Here's a snippet of the front-end code:
```typescript
const response = await fetch();
if(response.body) {
    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let fullText = ''
    while (true) {
        const { value, done } = await reader.read()
        if (done) {
            break
        } else {
            const chunk = decoder.decode(value)
            fullText += chunk
            if (onText) {
                onText({ text: fullText, cancel })
            }
        }
    }
}
```

## Specifications

- Version: 
@google/generative-ai: 0.1.3
node: 20.10.0

**Comment by hsubox76** [comment]
The `result.stream` property isn't a `ReadableStream`, it's an `AsyncGenerator<EnhancedGenerateContentResponse>`. Iterating over it using a `for` loop is the correct way to use it, as in your second example. Does it work as expected if you simply console.log `chunkText` instead of calling sseStream.write? If so, I don't think the problem is in the SDK code, which is returning a generator as expected - if you want to transform the generator back into a stream I think that's outside the scope of the SDK at the moment.

This seems to match other similar APIs such as the OpenAI streaming API: https://github.com/openai/openai-node?tab=readme-ov-file#streaming-responses-1

If you really need access to a stream object, you can propose it as a feature request, and describe your use case (including why you can't use the SDK directly from the front end).

**Comment by white-z** [comment]
> The `result.stream` property isn't a `ReadableStream`, it's an `AsyncGenerator<EnhancedGenerateContentResponse>`. Iterating over it using a `for` loop is the correct way to use it, as in your second example. Does it work as expected if you simply console.log `chunkText` instead of calling sseStream.write? If so, I don't think the problem is in the SDK code, which is returning a generator as expected - if you want to transform the generator back into a stream I think that's outside the scope of the SDK at the moment.
> 
> This seems to match other similar APIs such as the OpenAI streaming API: https://github.com/openai/openai-node?tab=readme-ov-file#streaming-responses-1
> 
> If you really need access to a stream object, you can propose it as a feature request, and describe your use case (including why you can't use the SDK directly from the front end).

I finally found the problem. It seems that HTTP cannot directly respond to the text generated by AsyncGenerator. Thank you for your suggestion; it has given me a deeper understanding of node.js
```typescript
  import { Readable } from 'stream'
  // ...
  const res = await chat.sendMessageStream(prompt)
  async function* generateText() {
    for await (const chunk of res.stream) {
      yield chunk.text()
    }
  }
  ctx.body = Readable.from(generateText())
```
