### ISSUE TITLE
How can I bypass safety block?

### ISSUE THREAD

**Issue by louislamme** [google/generative-ai-js#36]
I have such setting when calling the API
`exports.gemProVision = new GoogleGenerativeAI(
  process.env.GEN_AI_API_KEY
).getGenerativeModel({
  model: 'gemini-pro-vision',
  safety_settings: [
    {
      category: HarmCategory.HARM_CATEGORY_UNSPECIFIED,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_HARASSMENT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
  ],
})`

However I get the following:
`imageResp.response: {"promptFeedback":{"blockReason":"SAFETY","safetyRatings":[{"category":"HARM_CATEGORY_SEXUALLY_EXPLICIT","probability":"NEGLIGIBLE"},{"category":"HARM_CATEGORY_HATE_SPEECH","probability":"NEGLIGIBLE"},{"category":"HARM_CATEGORY_HARASSMENT","probability":"MEDIUM"},{"category":"HARM_CATEGORY_DANGEROUS_CONTENT","probability":"NEGLIGIBLE"}]}}`

And sometimes it returns:
`imageResp.response: {"promptFeedback":{"blockReason":"OTHER"}}`

I wonder what's the use of `threshold: HarmBlockThreshold.BLOCK_NONE` here?

**Comment by xiaohk** [comment]
Currently `HarmBlockThreshold.BLOCK_NONE` has no effect. The lowest threshold a developer can set is `HarmBlockThreshold.BLOCK_ONLY_HIGH`.

**Comment by louislamme** [comment]
Okay, I see. Thank you for your information :)

**Comment by kyeshmz** [comment]
@xiaohk is there a timeline to where this allows all threshholds?
