### ISSUE TITLE
generateContentStream ERROR: TypeError: response.body.pipeThrough is not a function

### ISSUE THREAD

**Issue by stackifyit** [google/generative-ai-js#43]
This works:
```
const genAI = new GoogleGenerativeAI(apiKey);
const genModel = genAI.getGenerativeModel({ 'gemini-pro' });
const result = await genModel.generateContent(content);
```

But when I stream, I get the error TypeError: response.body.pipeThrough is not a function:
```
const genAI = new GoogleGenerativeAI(apiKey);
const genModel = genAI.getGenerativeModel({ 'gemini-pro' });
//error occurs here
const result = await genModel.generateContentStream(content);
```

I am using node v21.3.0
npm version @google/generative-ai : "^0.1.3"

Thanks in advance!

**Comment by stackifyit** [comment]
Per [this answer](https://github.com/GoogleCloudPlatform/generative-ai/issues/353#issuecomment-1910609346), this is the correct place for this issue.

**Comment by 123jimin** [comment]
I've encountering the same problem for `ChatSession`'s `sendMessageStream`. (Node v20.5.1 and v20.11.0, @google/generative-ai 0.1.3, on Windows 10)

I'm not having the problem on Debian.

https://github.com/google/generative-ai-js/blob/main/packages/main/src/requests/stream-reader.ts#L38
At this line, it seems that `response.body` is an instance of `zlib.Gunzip`, not a `ReadableStream`.

https://github.com/google/generative-ai-js/blob/main/packages/main/src/requests/request.ts#L68
The request was created at this line.

**Comment by hoantran-it** [comment]
> I found the source of error. It's not a bug from this repo.
> 
> Another library I was using (`@mistralai/mistralai`) was incorrectly shimming fetch using `node-fetch`. `node-fetch` doesn't seem to be compatible with the Google AI SDK.
> 
> After I fixed it, the streaming seems to work well.

Can I confirm that you can use sendMessageStream without error, right? I don't have mistralai but I still have the error 😢

**Comment by 123jimin** [comment]
> Can I confirm that you can use sendMessageStream without error, right? I don't have mistralai but I still have the error 😢

Yes, I can use both `sendMessageStream` without problem.

    const genModel = client.getGenerativeModel({model: 'gemini-pro'});
    const chat = genModel.startChat({history: []});

    const result = await chat.sendMessageStream("What is the answer to the ultimate question of life, the universe, and everything?");
    for await(const chunk of result.stream) {
        console.log(chunk.text()); // also prints "42"
    }

Same for `generateContentStream`.

    const genModel = client.getGenerativeModel({model: 'gemini-pro'});
    const result = await genModel.generateContentStream("What is the answer to the ultimate question of life, the universe, and everything?");
    for await(const chunk of result.stream) {
        console.log(chunk.text()); // prints "42"
    }

There are a few ways you can check whether you are having the same problem with me:

- Check whether the lockfile (`package-lock.json`, `pnpm-lock.yaml`, or other files depending on the package manager you're using) contains `node-fetch` as a dependency.
- Use `npm ls --all` (warning: output is quite long) (or other similar commands for the package manager you're using) to check which library is using `node-fetch`.
- Just before calling `sendMessageStream`, put `console.log(fetch)` and check what it prints. On Node.js, it would print `[Function: fetch]` unless there is a polyfill involved.

**Comment by hoantran-it** [comment]
> > Can I confirm that you can use sendMessageStream without error, right? I don't have mistralai but I still have the error 😢
> 
> Yes, I can use `sendMessageStream` without problem.
> 
> ```
> const genModel = client.getGenerativeModel({model: 'gemini-pro'});
> const chat = genModel.startChat({history: []});
> 
> const result = await chat.sendMessageStream("What is the answer to the ultimate question of life, the universe, and everything?");
> for await(const chunk of result.stream) {
>     console.log(chunk.text()); // prints "42"
> }
> ```
> 
> Same for `generateContentStream`.
> 
> ```
> const genModel = client.getGenerativeModel({model: 'gemini-pro'});
> const result = await genModel.generateContentStream("What is the answer to the ultimate question of life, the universe, and everything?");
> for await(const chunk of result.stream) {
>     console.log(chunk.text()); // also prints "42"
> }
> ```
> 
> There are a few ways you can check whether you are having the same problem with me:
> 
> * Check whether the lockfile (`package-lock.json`, `pnpm-lock.yaml`, or other files depending on the package manager you're using) contains `node-fetch` as a dependency.
> * Use `npm ls --all` (warning: output is quite long) (or other similar commands for the package manager you're using) to check which library is using `node-fetch`.
> * Just before calling `sendMessageStream`, put `console.log(fetch)` and check what it prints. On Node.js, it would print `[Function: fetch]` unless there is a polyfill involved.
> * Use some other hacky ways to check whether `fetch` was modified; one example would be putting `globalThis.native_fetch = fetch` at the very start of your program (before including any other package) and check whether `globalThis.native_fetch === fetch` just before calling `sendMessageStream`.

Yes, I have **node-fetch** in the source code, I use it in another file like this

`
import fetch from 'node-fetch';
`

So the problem we have is that the streaming gets **node-fetch** instead of the original **fetch** of nodejs, right? Good clue for me to debug the issue, I will try this way tomorrow, thanks for the support @123jimin 🙏

**Comment by hoantran-it** [comment]
Checked the node-fetch and had no luck. The node-fetch was there for a long time, and I could run the streaming normally before 😞

**Comment by hoantran-it** [comment]
Yes, you're correct @123jimin the issue caused by this https://github.com/cohere-ai/cohere-typescript/issues/113

I will follow up there, thank you! 🙏

**Comment by stackifyit** [comment]
So once this repo updates the [cohere-typescript fix](https://github.com/cohere-ai/cohere-typescript/issues/113) to 7.7.4 and [@google/generative-ai](https://github.com/GoogleCloudPlatform/generative-ai) updates there related package to reflect this one, then the issue should be fixed?

**Comment by hoantran-it** [comment]
@stackifyit Yes, correct, you can try to debug in the code to see if anything modifies the original fetch, in my case, the Async is the original one

<img width="264" alt="Screenshot 2024-02-01 at 10 13 42" src="https://github.com/google/generative-ai-js/assets/13161875/52f53829-5fb2-428d-a904-37eb1fb3d909">

**Comment by raslasarslas** [comment]
> I found the source of error. It's not a bug from this repo.
> 
> Another library I was using (`@mistralai/mistralai`) was incorrectly shimming fetch using `node-fetch`. `node-fetch` doesn't seem to be compatible with the Google AI SDK.
> 
> After I fixed it, the streaming seems to work well.

Same for me, I modified it  and it's work now

**Comment by huytool157** [comment]
A lot of libraries shim `global.fetch` and fixing packages one by one can be a cat and mouse game? Has the Google team considered using `undici` rather than Node.js native fetch implementation instead? It's an extra library but native fetch is a [direct import](https://www.reddit.com/r/node/comments/11ntvfq/is_native_fetch_in_v18_faster_than_dedicated/) of `undici` itself? cc @hsubox76 

Right now we have to do something like this and it's pretty hacky:

```javascript
import undici from 'undici'

const currentFetch = global.fetch
global.fetch = undici.fetch

// streaming logic

global.fetch = currentFetch
```
