### ISSUE TITLE
Allow configuration of the BASE_URL

### ISSUE THREAD

**Issue by pnegahdar** [google/generative-ai-js#44]
```
const BASE_URL = "https://generativelanguage.googleapis.com";
```

The [BASE_URL](https://github.com/google/generative-ai-js/blob/985e01a0f1629a58287a2c6df71f6c7af91b18fa/packages/main/src/requests/request.ts#L20) is not configurable. 

It'd be helpful to make it so for passthrough proxies as needed. Also useful for testing and mocking out with local listeners if needed.

**Comment by hsubox76** [comment]
Duplicate of https://github.com/google/generative-ai-js/issues/25. Feel free to add your comment describing your use cases in that issue, it will help us make the case for it.
