### ISSUE TITLE
Allow API_VERSION in the Configuration

### ISSUE THREAD

**Issue by aroytman** [google/generative-ai-js#58]
## Expected Behavior

Ability to specify API_VERSION (for example: "v1beta") as a configuration.

## Actual Behavior

Currently the API_VERSION is hardcoded in the package to "v1" and there is no way to change it. For example, "v1beta" has functionality, such as function calling, that is currently inaccessible due to this hardcoded value.

**Comment by lahirumaramba** [comment]
Fixed in #56
