### ISSUE TITLE
Newest version breaks quickstart documentation

### ISSUE THREAD

**Issue by bakkot** [google/generative-ai-js#61]
## Expected Behavior

The code on [this page](https://ai.google.dev/tutorials/node_quickstart#streaming) should work.

## Actual Behavior

```
TypeError: Cannot use 'in' operator to search for 'text' in H
    at validateChatHistory ([...]@google/generative-ai/dist/index.mjs:758:25)
```

## Steps to Reproduce the Problem

Run the code from the sample:

```js
const { GoogleGenerativeAI } = require("@google/generative-ai");

// Access your API key as an environment variable (see "Set up your API key" above)
const genAI = new GoogleGenerativeAI(process.env.API_KEY);

async function run() {
  // For text-only input, use the gemini-pro model
  const model = genAI.getGenerativeModel({ model: "gemini-pro"});

  const chat = model.startChat({
    history: [
      {
        role: "user",
        parts: "Hello, I have 2 dogs in my house.",
      },
      {
        role: "model",
        parts: "Great to meet you. What would you like to know?",
      },
    ],
    generationConfig: {
      maxOutputTokens: 100,
    },
  });

  const msg = "How many paws are in my house?";

  const result = await chat.sendMessage(msg);
  const response = await result.response;
  const text = response.text();
  console.log(text);
}

run();
```

## Specifications

- Version: `@google/generative-ai": "^0.3.0`
- Platform: node

---

Specifically, I believe this was broken by https://github.com/google/generative-ai-js/pull/32. It would be trivial to make that change backwards-compatible by having `validateChatHistory` branch on whether `parts` is a string or array (or otherwise error), but either way the documentation should be updated.

**Comment by AjBillel** [comment]
@bakkot yep right, it was an issue with the latest version 

I try using an older version of gemini, it works for me 

`<script type="importmap">
      {
        "imports": {
          "@google/generative-ai": "https://esm.run/@google/generative-ai@0.2.1"
        }
      }
    </script>`

**Comment by khammami** [comment]
The documentation needs to be updated or as @bakkot said to make it backwards-compatible would be good too.
There's no need to use an older version, just update the JSON of chat history/prompt to match [function calling](https://ai.google.dev/docs/function_calling) new format.

```javascript
const chat = model.startChat({
    history: [
      {
        role: "user",
        parts: [{
                   "text": "Hello, I have 2 dogs in my house."
               }],
      },
      {
        role: "model",
        parts:[{
                   "text": "Great to meet you. What would you like to know?"
                }],
      },
    ],
    generationConfig: {
      maxOutputTokens: 100,
    },
  });
```

**Comment by alx13** [comment]
Quick start documentation is now updated to reflect changes in PR
