### ISSUE TITLE
function calling

### ISSUE THREAD

**Issue by roscoevanderboom** [google/generative-ai-js#66]
Has function calling been implemented? I can see the type definitions in the package but it doesn't seem to be working. I receive this error:

[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent: [400 ] Invalid JSON payload received. Unknown name "tools": Cannot find field. [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"description":"Invalid JSON payload received. Unknown name \"tools\": Cannot find field."}]}]

I highly recommend looking at the "runTools" method in the openai npm package. It makes functions calling very intuitive with many useful helpers. It adds significant improvements over the traditional function calling approach. 

Mainly that, in the traditional approach, to receive a streaming response from a function call, the user needs to manually disable function calling since the chat.completion is unable to stream a response when calling a function. In order to get a streaming response, the client needs to first call the functions, get a response and then call the api again, with the function response, to get a streaming response from the model.

"runTools" solves this attaching helper events to the method.

**Comment by CongVan** [comment]
Same with me. Pass tools as params to generateContent or generateContentStream doesn't work. But it work with basic curl with JSON content type

**Comment by rpsjr** [comment]
the same here

**Comment by alx13** [comment]
Function calling is in Beta release.

You need to specify `apiVersion` when initialising the model.

Please refer to https://github.com/google/generative-ai-js/blob/main/samples/node/advanced-function-calling.js#L52

**Comment by CongVan** [comment]
> Function calling is in Beta release.
> 
> You need to specify `apiVersion: 'v1beta'` when initialising the model.
> 
> Please refer to https://github.com/google/generative-ai-js/blob/main/samples/node/advanced-function-calling.js#L52

Thank @alx13 , it works now.

**Comment by roscoevanderboom** [comment]
Confirmed. Thanks @alx13
