### ISSUE TITLE
chat-session.ts Uncaught (in promise) Error: [400 ] 

### ISSUE THREAD

**Issue by gaodeng** [google/generative-ai-js#7]
The sendMessageStream methods in the ChatSession class do not handle promise rejections, potentially leading to unhandled promise rejections if generateContentStream fail. The internal promise chain does not have a .catch() to handle these errors, and they are not propagated to be catchable by the caller's try-catch block.

https://github.com/google/generative-ai-js/blob/7d119446081bb193c3178fd285d64950d6627645/packages/main/src/methods/chat-session.ts#L140

**Comment by hsubox76** [comment]
Thanks. We should catch this and not throw. There's a console.warn message already to let users know there's something wrong and they should inspect the response, and users can also catch `text()`.

Should also ensure the same is applied to `sendMessage()`.
