### ISSUE TITLE
NodeJS SDK - ChatSession with Function Calling

### ISSUE THREAD

**Issue by a4to** [google/generative-ai-js#70]
Function calling is in Beta release.

You need to specify `apiVersion: 'v1beta'` when initialising the model.

Please refer to https://github.com/google/generative-ai-js/blob/main/samples/node/advanced-function-calling.js#L52

_Originally posted by @alx13 in https://github.com/google/generative-ai-js/issues/66#issuecomment-2004064493_
            
            
            
Is there by any chance any examples using function calling in multi-turn conversations? Im sure it can be done, im just finding documentation quite hard to come by and i would love to stop guessing

Any insight would be immensely appreciated

```
class Agent {
  constructor() {
    this.history = [];
    this.model = genAI.getGenerativeModel({ model: "gemini-pro", tools, generationConfig, safetySetting }, { apiVersion: "v1beta" });
    this.chat = model.startChat({ history: this.history });
    this.browser = new AIB();
  }

  async runFunction(name, args) {
    const fn = functions[name];
    if (!fn) {
      throw new Error(`Unknown function "${name}"`);
    }

    const fr = {
      role: "function",
      parts: [
        {
          functionResponse: {
            name,
            response: {
              name,
              content: await functions[name](args)
            }
          },
        }
      ]
    };

    this.history.push(fr);
    return fr;
  }


  async msg(query) {
    let result = await this.chat.sendMessage(query);
    if(result?.response?.candidates[0]?.content) {
      let cont = false;
      if(result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
        cont = true;
        while(cont) {
          let { name, args } = result.response.candidates[0].content.parts[0].functionCall;
          let response = await this.runFunction(name, args);
          result = await this.chat.sendMessage([response]);
          if(!result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
            cont = false;
          }
        }
      }
    }
  }
}

```
GoogleGenerativeAIError: [400 Bad Request] Invalid JSON payload received. Unknown name "role" at 'contents[5].parts[0]': Cannot find field.
Invalid JSON payload received. Unknown name "parts" at 'contents[5].parts[0]': Cannot find field. [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"contents[5].parts[0]","description":"Invalid JSON payload received. Unknown name \"role\" at 'contents[5].parts[0]': Cannot find field."},{"field":"contents[5].parts[0]","description":"Invalid JSON payload received. Unknown name \"parts\" at 'contents[5].parts[0]': Cannot find field."}]}]

or if possibly someone notices where im going wrong here 🙏🏼

**Comment by a4to** [comment]
```
    const fr = {
      role: "function",
      parts: [
        {
          functionResponse: {
            name,
            response: {
              name,
              content: await functions[name](args)
            }
          },
        }
      ]
    };
```

This code is straight from the /samples/node/advanced-function-calling.js file, works in single turn setting but seems as seems to be failing when used in a longer history where the first function response is added to the history:

```
 {
    "role": "user",
    "parts": [
      {
        "text": "browse the web for some new cooking ideas, and look around the site for contact information"
      }
    ]
  },
  {
    "parts": [
      {
        "functionCall": {
          "name": "useBrowser",
          "args": {
            "data": {
              "url": "https://cookieandkate.com"
            },
            "action": "goto"
          }
        }
      }
    ],
    "role": "model"
  },
  {
    "role": "function",
    "parts": [
      {
        "functionResponse": {
          "response": {
            "content": {
              "success": true,
              "response": true
            }
          }
        }
      }
    ]
  }
]
/home/nvx1/PROJECTS/newGooG/node_modules/@google/generative-ai/dist/index.js:644
        for (const partOrString of request) {
                                   ^

TypeError: request is not iterable
    at formatNewContent (/home/nvx1/PROJECTS/newGooG/node_modules/@google/generative-ai/dist/index.js:644:36)
    at ChatSession.sendMessage (/home/nvx1/PROJECTS/newGooG/node_modules/@google/generative-ai/dist/index.js:839:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Agent.msg (/home/nvx1/PROJECTS/newGooG/app.js:237:20)
    at async /home/nvx1/PROJECTS/newGooG/app.js:262:3

Node.js v21.7.1
```

**Comment by hsubox76** [comment]
The code you're seeing the error from seems to not come from the history being passed in but from the argument being passed to `chat.sendMessage()`. In the first code snippet you have it as `query`, an arg passed to `msg()`. What does `query` look like here? It needs to be type `string | Array<string | Part>`.

**Comment by a4to** [comment]
thank you for the response, would you maybe expand on the formatting mentioned please? not 100% clear on what is meant by `string | Array<string | Part>`, its not a particular hard coded query, its a stringified array of ui elements and their selectors, but irrispective of the particular scenario, it never gets past the first functionResponse

How are you supposed to pass the functionResponse to the chat? because in the above i believe im sending the function response with the `chat.sendMessage(functionResponse)`

Really does not matter, i can adapt the workflow however necessary, would just be great to possibly see an example of a multi-turn flow where function response(s) are passed back to the model

Many thanks

**Comment by a4to** [comment]
```async msg(query) {
    let result = await this.chat.sendMessage(query);
    if(result?.response?.candidates[0]?.content) {
      let cont = false;
      if(result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
        cont = true;
        while(cont) {
          let { name, args } = result.response.candidates[0].content.parts[0].functionCall;
          ```
          
          Then here => `let response = await this.runFunction(name, args);` (runs the function and returns the `fr` object)
          
          Then contunues to pass that object directy to the chat.sendMessage: => 
          `result = await this.chat.sendMessage(response);`
          
          This explains the iteration error, if the object is placed into an array when sendMessage is called, ie: `chat.sendMessage([obj])`, it gets rid of the iteration error, but leaves me with:
          ```GoogleGenerativeAIError: [400 Bad Request] Invalid JSON payload received. Unknown name "role" at 'contents[5].parts[0]': Cannot find field.
Invalid JSON payload received. Unknown name "parts" at 'contents[5].parts[0]': Cannot find field. [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"contents[5].parts[0]","description":"Invalid JSON payload received. Unknown name \"role\" at 'contents[5].parts[0]': Cannot find field."},{"field":"contents[5].parts[0]","description":"Invalid JSON payload received. Unknown name \"parts\" at 'contents[5].parts[0]': Cannot find field."}]}]```

Hence circiling back to my initial dilema of guessing what the `fr` object should look like, if its supposed to be an object, and how it is intended to be passed back to the chat 
       
   ...continues       
          ```if(!result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
            cont = false;
          }
        }
      }
    }
  }```


Thanks again

**Comment by hsubox76** [comment]
Does this help?

```
async function functionCalling() {
  function nickname(name) {
    return `${name}erino!`;
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const fnModel = genAI.getGenerativeModel(
    {
      model: "gemini-pro",
      tools: {
        functionDeclarations: [
          {
            name: "nickname",
            parameters: {
              type: "OBJECT",
              description: "Give user a nickname",
              properties: {
                name: { type: "STRING", description: "the user's name" },
              },
            },
          },
        ],
      },
    },
    { apiVersion: "v1beta" }
  );
  const chat = fnModel.startChat();
  const result = await chat.sendMessage("My name is Fred. Can you give me a nickname?");
  const functionCall = result.response.candidates[0].content.parts[0].functionCall;
  const username = functionCall.args.name;
  const result2 = await chat.sendMessage([{ functionResponse: {
    name: 'nickname',
    response: { nickname: nickname(username) }
  } }]);
  console.log(result2.response.text());
}

functionCalling();
```

The reference docs aren't the most user-friendly (autogenerated) but they should be able to help you in cases like these. If you go to the [page for ChatSession.sendMessage](https://github.com/google/generative-ai-js/blob/main/docs/reference/generative-ai.chatsession.sendmessage.md) it shows you that one of the types you can pass is an Array of `Parts` and it links to `Part`, and if you follow that link, it shows you one of the types of `Part` is a `FunctionResponsePart`, and you can click on that and see what the structure looks like (which you can also see in the example above).

**Comment by a4to** [comment]
Youre a wizard `:)`

So yes that is exactly what i needed, thank you, i had:
```
    const fr = {
      role: "function",
      parts: [
        {
          functionResponse: { response: { content: res } }
        }
      ]
    };
```

Instead of

```
    const fr = [{
      functionResponse: {
        name,
        response: { content: res }
      }
    }];
```

coupled with an outdated SDK

Thank you very much @hsubox76, Genuinely!

**Comment by nbonamy** [comment]
Is there anyway to get function calling with streaming? When I call chat.sendMessageStream with functionResponse it fails. Thanks!

**Comment by jchoxha** [comment]
> Is there anyway to get function calling with streaming? When I call chat.sendMessageStream with functionResponse it fails. Thanks!

@nbonamy Have you figured this out?

**Comment by a4to** [comment]
Whats going wrong? So @hsubox76 gave a complete example above thats quite accurately demonstrates the practical implementation:

```
  async runFunction(name, args) {
    const fn = functions[name];
    if (!fn) {
      throw new Error(`Unknown function "${name}"`);
    }

    let res = await functions[name](args);

    const fr = [{
      functionResponse: {
        name, response: { content: res }
      }
    }];


    log(`:g:[+] :m:${name} :y:completed\n\n:m:-----\n\n:x:${JSON.stringify(fr, null, 2)}\n\n:m:-----\n\n`);
    return fr;
  }

  async msg(query) {
    let result = await this.chat.sendMessage(query);
    if(result?.response?.candidates[0]?.content) {
      log(`:g:[+] :m:Response :y:completed\n\n:m:-----\n\n:x:${JSON.stringify(result, null, 2)}\n\n:m:-----\n\n`);
      let cont = false;
      if(result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
        cont = true;
        while(cont) {
          let { name, args } = result.response.candidates[0].content.parts[0].functionCall;
          let response = await this.runFunction(name, args);
          result = await this.chat.sendMessage(response);
          if(!result?.response?.candidates[0]?.content?.parts[0]?.functionCall) {
            cont = false;
          }
        }
      }
    }
    return result;
  }
```



and

```
const tools = [{ functionDeclarations }];
const surveyTools = [{ functionDeclarations: [functionDeclarations[2]] }];

const generationConfig = {
  temperature: 0.1,
  maxOutputTokens: 40960
};


const model = genAI.getGenerativeModel({ model: "gemini-pro", tools, generationConfig, safetySetting }, { apiVersion: "v1beta", safetySetting });
```


that should do the trick, im not sure if this is still in beta, i havnt had trouble since i implimented this so havnt had reason to change it


Hope this helps 👍🏼👍🏼

**Comment by a4to** [comment]
just note these methods are defined within a class - hence the syntax, and some of the other fucntions such as log are obviously not present, but the just is the same  if you have a basic understanding of node and javascript im sure thats will be intelligible

**Comment by jchoxha** [comment]
> just note these methods are defined within a class - hence the syntax, and some of the other fucntions such as log are obviously not present, but the just is the same if you have a basic understanding of node and javascript im sure thats will be intelligible

I was asking @nbonamy if he figured out how to do this with sendMessageStream as it seems to behave differently from sendMessage.

**Comment by a4to** [comment]
> > just note these methods are defined within a class - hence the syntax, and some of the other fucntions such as log are obviously not present, but the just is the same if you have a basic understanding of node and javascript im sure thats will be intelligible
> 
> I was asking @nbonamy if he figured out how to do this with sendMessageStream as it seems to behave differently from sendMessage.

Try using generateContentStream instead? @jchoxha 

```
  async *genStream(query = this.task, history = this.history) {
    let res, count = 0, response = '', reg = new RegExp(/^````?[a-zA-Z ]*/), firstPart = true;
    console.log('\n\x1b[33;1m[?]\x1b[37m Starting Stream...\x1b[0m\n');

    history = this.formatHistory(history, 'chat');
    const model = this.models['text'];

    while (count < 4) {
      try {
        const result = await model.generateContentStream({ contents: [...history, { role: 'user', parts: query }] });
        for await (const chunk of result.stream) {
          let ch = chunk.text()?.toString()?.replace(reg, '').replace(/````?$/, '');
          if(firstPart) ch = ch.replace(new RegExp(`^\\[?${this.bot.title}\\]?:? ?`), '');
          response += ch;
          yield ch;
        }
        break;
      } catch (e) {
        count++;
        continue;
      }
    }
    if(count === 3) throw new Error('Failed to connect to the model');
    yield '__END_OF_STREAM__';
    await Stream.updateOne({ streamId: this.streamId }, { $push: { history: { role: 'model', parts: response } } });
    return response;
  }
```


Not the exact implimentation but im sure ive implimented this into a production application similarly with function calling, ill see if i can find it 👍🏼

What helped me a lot was just using the node cli and doing a type check on the various function calls and objects/methods. Object.keys(x).map(key => console.log(`${key}: ${x[key]}`))

good luck

**Comment by nbonamy** [comment]
> > Is there anyway to get function calling with streaming? When I call chat.sendMessageStream with functionResponse it fails. Thanks!
> 
> @nbonamy Have you figured this out?

Not. Did not try further. Yet.

**Comment by nbonamy** [comment]
Ok went back at it with version 0.21 still without luck. As suggested by @a4to switched to `generateContentStream` and got it working!
