### ISSUE TITLE
[TypeError: Cannot read property 'pipeThrough' of undefined] 

### ISSUE THREAD

**Issue by turkergercik** [google/generative-ai-js#79]
I cant use "await chat.sendMessageStream(newmessage.text)" in react native app. It gives 
 "[TypeError: Cannot read property 'pipeThrough' of undefined] " error.

"await chat.sendMessage(newmessage.text)" works fine.

  ```
const genAI = new GoogleGenerativeAI(API_KEY);
  const model = genAI.getGenerativeModel({ model: "gemini- 
 pro",safetySettings:safetySettings,generationConfig:generationConfig});
  const chat = model.startChat({safetySettings:safetySettings,history:history.current})
  const result = await chat.sendMessage(newmessage.text).catch((e)=>{
      console.log(e)
    })
    let text = '';
  for await (const chunk of result.stream) {
  const chunkText = chunk.text();
  console.log(chunkText);
  text += chunkText;
  }
  
    console.log(text);
```

**Comment by Ekrekr** [comment]
If you don't care about chunking like me, just swap `generateContentStream` for `generateContent` to avoid streaming.

https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.publishers.models/generateContent
