### ISSUE TITLE
do not expose API key in Error

### ISSUE THREAD

**Issue by haraldschilly** [google/generative-ai-js#8]
## Expected Behavior

No API key in error message

## Actual Behavior

Just see where `url` comes from in that line: https://github.com/google/generative-ai-js/blob/7d119446081bb193c3178fd285d64950d6627645/packages/main/src/requests/request.ts#L88

## Specifications

- Version: 0.1.1 on Linux
- Platform: Node 18

**Comment by marb2000** [comment]
Thank you for submitting this request! It is reasonable not to expose the API Key in the error, and we will take a look at and evaluate it. In case that it meets the bar, it’s reasonable to fix it within the GA release of the SDK - no confirmed date yet.
