### ISSUE TITLE
Request options are not passed to modelInstance.countTokens 

### ISSUE THREAD

**Issue by arjunattam** [google/generative-ai-js#98]
My understanding is that the library requires `apiVersion` to be set to `v1beta` for Gemini 1.5 to work. However, the `apiVersion` is not passed down to the implementation of `countTokens`, due to which it makes a request at the older endpoint.

This is with v0.6.0 (latest)

## Actual Behavior

```js
const modelInstance = googleAI.getGenerativeModel(
    { model: "gemini-1.5-pro-latest" },
    { apiVersion: "v1beta" },
  )

modelInstance.generateContent()
// this sends a request to https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent
// ...

modelInstance.countTokens
// this sends a request to https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro-latest:countTokens()
// which errors out
```

I believe the issue lies here (`requestOptions` are not passed): https://github.com/google/generative-ai-js/blob/79b7651547536183108f0b78791761d1ece01f88/packages/main/src/models/generative-model.ts#L156

## Expected Behavior

The `countTokens` method should make a request to the v1beta endpoint

**Comment by hsubox76** [comment]
Thanks for finding this, will get this fixed soon.

**Comment by zakcali** [comment]
is this sequence behaves correct? I'm using this parameters:
`    const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest",  systemInstruction: { role: "system", parts: [{ text: "your name is bob" }] }, }, { apiVersion: 'v1beta', generationConfig, safetySettings });`
